# Generated by Django 4.0.1 on 2022-01-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', 'created']},
        ),
    ]
