# Generated by Django 4.0.1 on 2022-01-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='count',
        ),
    ]
